### ISSUE TITLE
Using multiple bam files for scaffolding?

### ISSUE THREAD

**Issue by Jigyasa3** [marbl/bambus3#13]
Hey! 

Thank you for the amazing software! I wanted to ask if it can be applied to two bam files? For example, I have two metaSPAdes assembly files for the same sample which I want to combine together to get better scaffolds (i.e. one final file). I can generate two bam files for each assembly, but can they be used together in MetaCarvel to get better scaffolds?

Looking forward to your reply!

**Comment by hsmurali** [comment]
Were these two assemblies built on two different sets of reads? In that case the two bam files can be merged and their corresponding contigs can be merged into a single file before running metacarvel. On the other hand if these two assemblies were built on the same set of reads metacarvel might face difficulties in creating links between to contigs due to multimapping of reads.

**Comment by Jigyasa3** [comment]
Thank you for replying! Will do that!

**Comment by hsmurali** [comment]
Closing this issue
